config/routes.rb
Illumine::Application.routes.draw do

  resources :news_items

  get 'news', to: 'viewable#news'

  root to: 'viewable#home'
  resources :users
  resources :sessions

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
end

app/models/news_item.rb
class NewsItem < ActiveRecord::Base
  attr_accessible :description, :image, :title, :url
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password, :password_confirmation
  has_secure_password
  
  validates_uniqueness_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/news_items_controller.rb
class NewsItemsController < ApplicationController
  # GET /news_items
  # GET /news_items.json
  def index
    @news_items = NewsItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @news_items }
    end
  end

  # GET /news_items/1
  # GET /news_items/1.json
  def show
    @news_item = NewsItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @news_item }
    end
  end

  # GET /news_items/new
  # GET /news_items/new.json
  def new
    @news_item = NewsItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @news_item }
    end
  end

  # GET /news_items/1/edit
  def edit
    @news_item = NewsItem.find(params[:id])
  end

  # POST /news_items
  # POST /news_items.json
  def create
    @news_item = NewsItem.new(params[:news_item])

    respond_to do |format|
      if @news_item.save
        format.html { redirect_to @news_item, notice: 'News item was successfully created.' }
        format.json { render json: @news_item, status: :created, location: @news_item }
      else
        format.html { render action: "new" }
        format.json { render json: @news_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /news_items/1
  # PUT /news_items/1.json
  def update
    @news_item = NewsItem.find(params[:id])

    respond_to do |format|
      if @news_item.update_attributes(params[:news_item])
        format.html { redirect_to @news_item, notice: 'News item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @news_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news_items/1
  # DELETE /news_items/1.json
  def destroy
    @news_item = NewsItem.find(params[:id])
    @news_item.destroy

    respond_to do |format|
      format.html { redirect_to news_items_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  unless User.all == [] || User.first == nil
    before_filter :authorize
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end
end

app/controllers/viewable_controller.rb
class ViewableController < ApplicationController
  def home
    @news = NewsItem.all(order: 'created_at DESC')
    # @skills = Skill.all(order: 'level DESC')
    # @experiences_odd = Experience.where("sort_order % 2 = ?", "1").order("sort_order ASC")
    # @experiences_even = Experience.where("sort_order % 2 = ?", "0").order("sort_order ASC")

    # size = 3
    # @games = Game.all(order: 'length_of_play DESC')
    # @games1 = (size - 3).step(@games.size - 1, size).map { |i| @games[i] }
    # @games2 = (size - 2).step(@games.size - 1, size).map { |i| @games[i] }
    # @games3 = (size - 1).step(@games.size - 1, size).map { |i| @games[i] }

    # @code_samples = CodeSample.all(order: "sort_order ASC")
  end

  def news
    @news = NewsItem.all(order: 'created_at DESC')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_items_helper.rb
module NewsItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Illumine" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% if current_user %>
      <nav class="top-bar" style="box-shadow: 0 0 15px #222;">
        <section class="top-bar-section">
          <h3 class="left" style="color: white; padding: 6px 0 0 20px; font-size: 20px;"><%= link_to current_user.username, root_path, style: "color: #eee;" %></h3>
          <ul class="right">
            <li class="divider"></li>
            <li><%= link_to "News", news_items_path %></li>
            <li class="divider"></li>
            <li class="has-form"><%= link_to "Log Out", logout_path, class: "button secondary radius", style: "line-height: 18px; font-size: 13px;" %></li>
          </ul>
        </div>
      </nav>
    <% end %>

    <div id="title-box">
      <h1>Illumine</h1>
    </div>

    <div class="row" id="flash_container">
      <% flash.each do |name, msg| %>

        <% if name.to_s == "alert" %>
          <div data-alert id="error_alert" class="large-12 large-centered columns alert-box alert radius" style="padding: 8px; margin: 3px auto; text-align:center;">   
            <%= msg %>
            <a href="#" class="close">&times;</a>
          </div>
        <% end %>

        <% if name.to_s == "notice" %>
          <div data-alert id="succes_alert" class="large-12 large-centered columns alert-box success radius" style="padding: 8px; margin: 3px auto; text-align:center;">
            <%= msg %>
            <a href="#" class="close">&times;</a>
          </div>
        <% end %>

        <% if name.to_s == "error" %>
          <div data-alert id="notice_alert" class="large-12 large-centered columns alert-box radius" style="padding: 8px; margin: 3px auto; text-align:center;">
            <%= msg %>
            <a href="#" class="close">&times;</a>
          </div>
        <% end %>
      <% end %>
    </div>

    <div id="page">
      <div class="large-2 columns">
        <ul class="main-navigation side-nav">
          <li><%= link_to "News", news_path %></li>
          <li><a href="#">Link 2</a></li>
          <li><a href="#">Link 3</a></li>
          <li><a href="#">Link 4</a></li>
        </ul>
      </div>
      <div class="large-10 columns main-content-area"><%= yield %></div>
    </div>

    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/news_items/_form.html.erb
<%= form_for(@news_item) do |f| %>
  <% if @news_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news_item.errors.count, "error") %> prohibited this news_item from being saved:</h2>

      <ul>
      <% @news_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news_items/edit.html.erb
<h1>Editing news_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @news_item %> |
<%= link_to 'Back', news_items_path %>

app/views/news_items/index.html.erb
<h1>Listing news_items</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Url</th>
    <th>Image</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @news_items.each do |news_item| %>
  <tr>
    <td><%= news_item.title %></td>
    <td><%= news_item.url %></td>
    <td><%= news_item.image %></td>
    <td><%= news_item.description %></td>
    <td><%= link_to 'Show', news_item %></td>
    <td><%= link_to 'Edit', edit_news_item_path(news_item) %></td>
    <td><%= link_to 'Destroy', news_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New News item', new_news_item_path %>

app/views/news_items/new.html.erb
<h1>New news_item</h1>

<%= render 'form' %>

<%= link_to 'Back', news_items_path %>

app/views/news_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @news_item.title %>
</p>

<p>
  <b>Url:</b>
  <%= @news_item.url %>
</p>

<p>
  <b>Image:</b>
  <%= @news_item.image %>
</p>

<p>
  <b>Description:</b>
  <%= @news_item.description %>
</p>


<%= link_to 'Edit', edit_news_item_path(@news_item) %> |
<%= link_to 'Back', news_items_path %>

app/views/users/new.html.erb
<div class="large-9 large-centered columns">
  <%= form_for @user, html: {:class => "custom", :'data-abide' => ''} do |f| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <% @user.errors.full_messages.each do |message| %>
          <div data-alert id="succes_alert" class="large-9 large-centered columns alert-box alert radius" style="padding: 8px; margin: 0 auto 20px auto; text-align:center;">
            <%= message %>
            <a href="#" class="close">&times;</a>
          </div>
        <% end %>
      </div>
    <% end %>

    <h2 style="text-align:center; margin-top: 50px;">Create User</h2>
    <div class="row">
      <div class="large-3 columns">
        <%= f.label :username, "Username: ", class: "inline right", style: "margin-right: 20px;" %>
      </div>
      <div class="large-7 columns left">
        <%= f.text_field :username, required:'' %>
        <small class="error">Can't be blank</small>
      </div>
    </div>
    <div class="row">
      <div class="large-3 columns">
        <%= f.label :password, "Password: ", class: "inline right", style: "margin-right: 20px;" %>
      </div>
      <div class="large-7 columns left">
        <%= f.password_field :password, required:'' %>
        <small class="error">Password must have at least 8 characters <br>And include at least 1 Capital Letter and 1 number</small>
      </div>
    </div>
    <div class="row">
      <div class="large-3 columns">
        <%= f.label :password_confirmation, "Password Confirmation: ", class: "inline right", style: "margin-right: 20px;" %>
      </div>
      <div class="large-7 columns left">
        <%= f.password_field :password_confirmation, required:'' %>
        <small class="error">Must match Password</small>
      </div>
    </div>
    <div class="row" style="margin-top: 65px;">
      <div class="large-8 large-centered columns"> 
        <div class="large-5 columns left">   
          <%= link_to 'Cancel', root_path, class: "button radius expand alert" %>
        </div>
        <div class="large-5 columns right">      
          <%= f.submit "Submit", class: "button radius expand" %>
        </div>
      </div>
    </div>
  <% end %>

</div>

app/views/viewable/news.html.erb
<h1>News</h1>
<% @news.each do |news_item| %>
  <div>
    <h3><%= news_item.title %></h3>
    <p><%= news_item.description %></p>
    <%= link_to "More...", "http://" + news_item.url %>
  </div>
<% end %>